config/routes.rb
Rails.application.routes.draw do
  root 'filters#index' #Home
  get 'filters/index'
  post 'filters/index'
  resources :results

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/filter.rb
class Filter < ApplicationRecord
end

app/models/result.rb
class Result < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/filters_controller.rb
class FiltersController < ApplicationController

  def index
    if params[:zip]
      @results = SearchDb.search(params[:zip], params[:reviews], params[:rating])
    else
      flash.notice = 'Nothing yet'
    end
    render :index
  end

  private

  def filter_params
    params.require(:filter).permit(:zip, :reviews, :rating, :cost, :enhanced, :carehome)
  end

end

app/controllers/results_controller.rb
class ResultsController < ApplicationController

  def index

  end

  def create
    @result = Result.find_or_create_by(resultId: result_params['resultId']) do |r|
      r.resultId = result_param["resultId"]
      r.name = result_param['name']
      r.address = result_param['address']
      r.postalCode = result_param['postalCode']
      r.enhanced = result_param['enhanced']
      r.careHome = result_param['careHome']
      r.description = result_param['description']
      r.averageCost = result_param['averageCost']
      r.averageRating = result_param['averageRating']
      r.foodRating = result_param['foodRating']
      r.reviews = result_param['reviews']
      r.url = result_param['url']
      r.websiteUrl = result_param['websiteUrl']
      r.phone = result_param['phone']
    end
  end

  private

  def result_params
    params.require(:result).permit(:resultId, :name, :address, :postalCode, :enhanced, :careHome, :description, :averageCost, :averageRating, :foodRating, :review, :url, :websiteUrl, :phone)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/filters_helper.rb
module FiltersHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/filters/index.html.erb
<h1>Filters#index</h1>
<p>Zip required, leave blank to ignore </p>
<%= form_tag(filters_index_path) do %>
  Zip <%= text_field_tag :zip  %>
  Reviews <%= text_field_tag :reviews %>
  Rating <%= text_field_tag :rating %>
  <%= submit_tag 'Search' %>
  <br>
  <p> Not implemented below <p>
  Cost <%= text_field_tag :cost %>
  Enhanced <%= check_box_tag :enhanced %>
  Carehome <%= check_box_tag :carehome %>

<% end %>
<% if !@results.nil? && @results.kind_of?(Array) %>
  <% @results.each do |res|%>
    <p><%= res['name'] %> </p>
    <p><%= res['addressLine1'] %> </p>
    <p><%= res['selfDescription'] %> </p>
    <p>Reviews:<%= res['reviewCount'] %> </p>
    <p>Rating:<%= res['averageRating'] %> </p>
    <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CaringFilters</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/results/index.html.erb
<h1>Results#index</h1>